/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: DatSketch (https://sketchfab.com/DatSketch)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/office-monitor-workstation-monitor-6a7b0147890242418a49f6db26657ab4
title: Office Monitor / Workstation Monitor
*/

import { useState } from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import type THREE from "three";

type GLTFResult = GLTF & {
  nodes: {
    group_0_Material001_0: THREE.Mesh;
    group_0001_Material001_0: THREE.Mesh;
    group_0002_layar_0: THREE.Mesh;
    SketchUp_material_0: THREE.Mesh;
    SketchUp001_Material002_0: THREE.Mesh;
    SketchUp003_Material002_0: THREE.Mesh;
    SketchUp002_Material003_0: THREE.Mesh;
    SketchUp004_Material003_0: THREE.Mesh;
  };
  materials: {
    ["Material.001"]: THREE.MeshStandardMaterial;
    layar: THREE.MeshStandardMaterial;
    material: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
  };
};

export function Screen(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("/scene.glb") as GLTFResult;
  const [hover, setHover] = useState(false);
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[2.8027, -38.9136, -25.1795]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={27.4641}
          >
            <group position={[2.7215, 0.3012, 10.7899]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.group_0_Material001_0.geometry}
                // material={materials["Material.001"]}
              >
                <meshStandardMaterial />
              </mesh>
            </group>
            <group position={[2.442, 6.74, 10.7488]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.group_0001_Material001_0.geometry}
                //material={materials["Material.001"]}
              >
                <meshStandardMaterial />
              </mesh>
            </group>
            <group position={[3.5672, -0.0025, 11.6677]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.group_0002_layar_0.geometry}
                onPointerOver={() => setHover(true)}
                onPointerOut={() => setHover(false)}
                onClick={() => alert("you tapped a screen")}
              >
                <meshBasicMaterial color={hover ? "#818cf8" : "#6366f1"} />
              </mesh>
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SketchUp_material_0.geometry}
              //material={materials.material}
            >
              <meshStandardMaterial />
            </mesh>
          </group>
          <group
            position={[0.878, -35.7159, -9.2863]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={27.4641}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SketchUp001_Material002_0.geometry}
              // material={materials["Material.002"]}
            >
              <meshStandardMaterial />
            </mesh>
          </group>
          <group
            position={[3.4539, 183.4313, -24.2365]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={27.4641}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SketchUp003_Material002_0.geometry}
              //material={materials["Material.002"]}
            >
              <meshStandardMaterial />
            </mesh>
          </group>
          <group
            position={[0.878, -35.7159, -9.2863]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={27.4641}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SketchUp002_Material003_0.geometry}
              //material={materials["Material.003"]}
            >
              <meshStandardMaterial />
            </mesh>
          </group>
          <group
            position={[0.878, -35.7159, -9.2863]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={27.4641}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SketchUp004_Material003_0.geometry}
              //material={materials["Material.003"]}
            >
              <meshStandardMaterial />
            </mesh>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.glb");
